# 配置 GitHub Releases 的发布说明生成方式

changelog:
  # 要从拉取请求中排除的作者（如机器人）和标签
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🛠 破坏性变更
      labels:
        - Semver-Major
        - breaking-change
    - title: 🎉 新功能
      labels:
        - Semver-Minor
        - enhancement
    - title: 🐞 错误修复
      labels:
        - bug
    - title: 👒 依赖更新
      labels:
        - dependencies
    - title: 其他变更
      labels:
        - "*"
