name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'  # 根据 bungee 模块要求使用 Java 17
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: |
          */target/*.jar
          !*/target/original-*.jar
          !*/target/*-shaded.jar
    - name: 创建 SHORT_SHA
      run: echo "github.sha=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
    - name: Create Release
      if: github.event_name != 'pull_request'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          */target/*.jar
          !*/target/original-*.jar
          !*/target/*-shaded.jar
        name: AutoRelease ${{ github.sha }}
        draft: false
        prerelease: false
        tag_name: ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
